# Generated by Django 3.2.9 on 2021-11-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=20)),
                ('Tasks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusoftask', models.CharField(max_length=20)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.todotasks')),
            ],
        ),
    ]
