# Generated by Django 3.2.9 on 2021-11-15 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20211115_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todotask',
            name='Task',
            field=models.CharField(max_length=100),
        ),
    ]
